#!/bin/sh

# GPIO test script on iMX6 jig board

RED="\\033[0;31m"
NOCOLOR="\\033[0;39m"
GREEN="\\033[0;32m"
GRAY="\\033[0;37m"
OK="${GREEN}OK$NOCOLOR"
FAIL="${RED}FAIL$NOCOLOR"
STATUS="PASS"

fail()
{
	STATUS="FAIL";
	echo -e "$@"
}

gpio_test_pair_num()
{
	if [ ! -d "/sys/class/gpio/gpio$1" ]; then
		echo $1 > /sys/class/gpio/export
	fi
	if [ ! -d "/sys/class/gpio/gpio$2" ]; then
		echo $2 > /sys/class/gpio/export
	fi
	echo in > /sys/class/gpio/gpio$2/direction
	echo out > /sys/class/gpio/gpio$1/direction

	echo 0 > /sys/class/gpio/gpio$1/value
	usleep 20000
	grep -q 0 /sys/class/gpio/gpio$2/value || fail "set 0 gpio $1 -> $2 $FAIL"

	echo 1 > /sys/class/gpio/gpio$1/value
	usleep 20000
	grep -q 1 /sys/class/gpio/gpio$2/value || fail "set 1 gpio $1 -> $2 $FAIL"

	echo in > /sys/class/gpio/gpio$1/direction
	echo in > /sys/class/gpio/gpio$2/direction
}

gpio_test_pair_bank()
{
	echo "Testing GPIO$1[$2] to GPIO$3[$4] raising and falling"
	gpio_test_pair_num $((($1-1)*32+$2)) $((($3-1)*32+$4))
}

if [[ ${SOMTYPE} == "DART-MX6" ]]; then
	gpio_test_pair_bank 1 5  4 19
	gpio_test_pair_bank 1 3  4 17
	gpio_test_pair_bank 3 30  4 18
	gpio_test_pair_bank 6 30  6 19
	gpio_test_pair_bank 6 24  6 26
	gpio_test_pair_bank 6 25  6 20
	gpio_test_pair_bank 6 27  6 21
	gpio_test_pair_bank 6 28  6 22
	gpio_test_pair_bank 6 29  6 23
	gpio_test_pair_bank 5 4  3 10
	gpio_test_pair_bank 6 6  2 22
	gpio_test_pair_bank 2 16  3 4
	gpio_test_pair_bank 2 18  3 1
	gpio_test_pair_bank 2 20  3 0
	gpio_test_pair_bank 2 19  2 29
	gpio_test_pair_bank 3 3  2 28
	gpio_test_pair_bank 3 2  2 21
	gpio_test_pair_bank 3 22  3 21
	gpio_test_pair_bank 1 31  5 6
	gpio_test_pair_bank 1 22  5 7
	gpio_test_pair_bank 1 23  5 8
	gpio_test_pair_bank 4 21  5 9
	gpio_test_pair_bank 4 22  5 10
	gpio_test_pair_bank 4 23  5 11
	gpio_test_pair_bank 4 24  5 12
	gpio_test_pair_bank 4 25  5 13
	gpio_test_pair_bank 4 26  5 14
	gpio_test_pair_bank 4 27  5 15
	gpio_test_pair_bank 4 28  5 16
	gpio_test_pair_bank 4 29  5 17
	gpio_test_pair_bank 4 16  2 17
	gpio_test_pair_bank 1 24  3 11

else # VAR-SOM-MX6 || VAR-SOM-SOLO/DUAL
	if [[ ${CPUTYPE} == "MX6DL" ]]; then
		PAD_EIM_D28_ADDR=0x020E0174
	else #${CPUTYPE} == "MX6Q"
		PAD_EIM_D28_ADDR=0x020E00C4
	fi

	# Disable BT UART and Audio buffers
	echo 122 > /sys/class/gpio/export
	echo 123 > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio122/direction
	echo out > /sys/class/gpio/gpio123/direction
	echo 1 > /sys/class/gpio/gpio122/value
	echo 1 > /sys/class/gpio/gpio123/value

	# Move CTS pin of BT to be GPIO
	devmem2 ${PAD_EIM_D28_ADDR} w 0x00000015 > /dev/null

	gpio_test_pair_bank 5 16  5 15
	if [[ ${SOMREV} != "SOM_REV_126" ]]; then
		gpio_test_pair_bank 5 13  3 5
		gpio_test_pair_bank 3 24  1 9
		if [[ ${SOMTYPE} != "SOMSOLO" ]]; then
			gpio_test_pair_bank 2 14  1 1
		fi
	fi

	gpio_test_pair_bank 1 7  1 8
	gpio_test_pair_bank 4 10  3 28
	gpio_test_pair_bank 3 26  3 25

	gpio_test_pair_bank 4 14  4 15
	gpio_test_pair_bank 3 20  3 19
	gpio_test_pair_bank 5 27  7 11
	gpio_test_pair_bank 1 4  1 5
	gpio_test_pair_bank 6 5  5 21
	gpio_test_pair_bank 5 20  5 30
	gpio_test_pair_bank 6 0  6 2

	# Move back CTS pin of BT to be CTS
	devmem2 ${PAD_EIM_D28_ADDR} w 0x00000004 > /dev/null
fi

echo ${STATUS}
