#!/bin/sh

if [[ $SOMTYPE == "DART-MX6" ]]; then
	modprobe g_ether
	sleep 1
	if [ "$(ifconfig -a | grep -c "usb")" -ne "2" ]; then
		echo "FAIL: USB or OTG in not responding."
		exit 1
	fi
	rmmod g_ether

else # VAR-SOM-MX6 || VAR-SOM-SOLO/DUAL
	if [ "$(lsusb | grep -c "10c4:ea60")" -ne "1" ]; then
		echo "FAIL: USBHOST device was not found!!! SOM Pins 108,110. CPU is not soldered well."
		exit 1
	fi
fi

echo "PASS"
