#!/bin/sh

/etc/init.d/bluetooth start

# Load firmware check. If pass then UART is soldered well.
RET=`/etc/init.d/variscite-bt | grep -c "Device setup complete"`
if [[ $RET = 0 ]]; then
	echo "FAIL: Cannot load firmware"
	exit 1
fi

# Check if the device is up
RET=`hcitool dev | grep -c hci`
if [[ $RET = 0 ]]; then
	echo "FAIL: Device is not up"
	exit 1
fi

echo "PASS"
