#!/bin/sh

LIMIT=$1
if [ -z "$1" ]; then
	LIMIT="55"
fi

SSID=$2
if [ -z "$2" ]; then
	SSID="JIGwireless"
fi

echo "Testing SSID $SSID"
echo "Signal limit is -${LIMIT}.00dBm"


ifconfig wlan0 up

for i in `seq 1 8`
do
        NUM_VAR=`./iwscan.sh | grep $SSID | cut -d, -f1 | cut -d. -f1 | cut -d- -f2`
	if [ -n "$NUM_VAR" ]; then
		if [[ $NUM_VAR < $LIMIT ]]; then
			echo PASS: Signal is -${NUM_VAR}.00dBm
			exit 0
		else
			echo Signal: -${NUM_VAR}.00dBm
		fi
	else
		echo No signal

	fi

	sleep 1
done

echo
./iwscan.sh
echo
echo FAIL
exit 1
